// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9lZEucchZ8biwkKG1tkoialPUz5eMwS8',
    appId: '1:360165740253:web:182bdb7ab0d13059221534',
    messagingSenderId: '360165740253',
    projectId: 'onbook-c4eae',
    authDomain: 'onbook-c4eae.firebaseapp.com',
    storageBucket: 'onbook-c4eae.firebasestorage.app',
    measurementId: 'G-DVVEF0Y4QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYq39a3F0IHdULWPekDy_7uubQVOLOOWQ',
    appId: '1:360165740253:android:879ab09c0e16d3ab221534',
    messagingSenderId: '360165740253',
    projectId: 'onbook-c4eae',
    storageBucket: 'onbook-c4eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3o259bdsXoLcFzgRUDyUqTuHYmgb8siU',
    appId: '1:360165740253:ios:e62f5d3d4f734509221534',
    messagingSenderId: '360165740253',
    projectId: 'onbook-c4eae',
    storageBucket: 'onbook-c4eae.firebasestorage.app',
    iosBundleId: 'com.example.onbookApp',
  );
}
